### ISSUE TITLE
Disable green line and border radius

### ISSUE THREAD

**Issue by huyhoang8398** [Deathemonic/Aesthetic-GTK#1]
is this possible to Disable the green line arround dialog and border radius

**Comment by Deathemonic** [comment]
Yes, because it's just css you can edit the source code and change it

**Comment by huyhoang8398** [comment]
Since im not familiar with css, can you guide me to remove these border 
![image](https://user-images.githubusercontent.com/25379882/173205365-1dce0e04-3e74-4a71-bd61-cb344a48b3ce.png)

**Comment by Deathemonic** [comment]
try going through the gtk3 main folder and edit the .css file and try to loook for this

```sh
.menu,
.context-menu {
  margin: 6px;
  padding: 6px;
  background-color: #0A1419;
  background-clip: border-box;
  border-radius: 12px;
  border: 1px solid #1b3745;
}
```

and edit which it says ``border: 1px solid #1b3745;`` to ``border: 0px solid #1b3745;`` or just remove it It should remove the borders

**Comment by huyhoang8398** [comment]
```
$window-radius: 0px;
$modal-radius: 0px;
$corner-radius: 0px;
$menu-radius: 0px;
$circular-radius: 0px;
```

can i edit `Aesthetic-GTK/src/sass/_variables.scss` so that i can remove all the border?

**Comment by Deathemonic** [comment]
yeah you can also do that if you want to
