### ISSUE TITLE
Text is hardly see in thunderbird

### ISSUE THREAD

**Issue by huyhoang8398** [Deathemonic/Aesthetic-GTK#2]
![image](https://user-images.githubusercontent.com/25379882/172871080-65e78c1e-b7d8-4eca-a0a9-8a333038e523.png)
selected item text is hardly see in thunderbird

**Comment by Deathemonic** [comment]
hey just fixed it try testing it out if it still has that bug

**Comment by huyhoang8398** [comment]
Nice , work perfect now

**Comment by Deathemonic** [comment]
well thanks for finding this issue, if you can anymore issue feel free to summit again
