### ISSUE TITLE
New Concept 

### ISSUE THREAD

**Issue by rxyhn** [Deathemonic/Aesthetic-GTK#3]
first of all i wanna say thanks you have created a nice gtk themes for my dotfiles, let's to the points, on the next rice i'll use macOS concept so how about updates the gtk themes to WhiteSur? so that it will supports the overall look. as we can see this gtk theme is based from [Colloid-gtk-theme](https://github.com/vinceliuice/Colloid-gtk-theme) is it possible to make this gtk based from [WhiteSur](https://github.com/vinceliuice/WhiteSur-gtk-theme)? so it'll more relatable and looks nice for an macOS concept.

**Comment by Deathemonic** [comment]
hmmm it's possible but should this be a new color scheme or just the same as the mac os one?

**Comment by Deathemonic** [comment]
this should be easy also should i also make a kvantum theme like whitesurkde if there's is one

**Comment by rxyhn** [comment]
> hmmm it's possible but should this be a new color scheme or just the same as the mac os one?

still with my night colorscheme

**Comment by rxyhn** [comment]
![screensht_22-06-16_10:34:50](https://user-images.githubusercontent.com/93292023/173985608-556fcc5a-4200-434b-816e-abf28b9629be.png)

a little leak

**Comment by Deathemonic** [comment]
ok! I think i can work with this, should i just leave whitesur as it is and just change the colorscheme or i should tweak some stuff and change the colorscheme

**Comment by Deathemonic** [comment]
there's also like icon packs with folders idk if i should also change the folder color scheme it might take long or just leave as it is

**Comment by rxyhn** [comment]
This rice will be released approximately within the next two weeks, that's quite a lot of time right? do whatever you think is good and doesn't burden you

**Comment by Deathemonic** [comment]
alright ill start working rm

**Comment by Deathemonic** [comment]
@rxyhn ill probably just recolor some stuff and tweak so it could be readable i won't be doing major stuff like removing nord and the other color scheme and cleaning the source code ill just recolor, package them with flatpak and gtk4 included

![image](https://user-images.githubusercontent.com/65948476/174084584-b8d2fcbb-6629-4e0d-b60e-891959b28b74.png)
sneekpeek still work in progress

**Comment by rxyhn** [comment]
yeaahhhhh alright, then can you move that window titlebar `close, maximize, minimize` placement to the left than on the right? is it possible?

**Comment by Deathemonic** [comment]
yeah it's possible

**Comment by Deathemonic** [comment]
probably the new nautilus update ill try installing gnome

**Comment by rxyhn** [comment]
> > just look like this WhiteSur showcase image, but idk why in my case too the window titlebar pos is on the right, so how to change the pos on the wm's?
> 
> if right position wont let's just disable the controls and set awesome title as the controls instead
> 
> like this: ![!](https://github.com/ChocolateBread799/dotfiles/raw/main/assets/workspace.jpg)

i've do that, what i want is some gtk app who had their default window titlebar to got left pos

**Comment by Deathemonic** [comment]
> ![Screenshot from 2022-06-16 21-19-08](https://user-images.githubusercontent.com/93292023/174090933-aa7e751f-eab2-4189-a15f-a0ed3388e34c.png)
> 
> works perfect on gnome

but in a window manager is doesn't

**Comment by Deathemonic** [comment]
maybe it's mutter that doing the fancy stuff and just spit out the default stuff when using another window manager beside mutter or maybe it's just the gnome shell

**Comment by rxyhn** [comment]
> maybe it's mutter that doing the fancy stuff and just spit out the default stuff when using another window manager beside mutter or maybe it's just the gnome shell

alright lets forgot about it, so just recolor and delete unimportant part, so the file won't be too big

**Comment by Deathemonic** [comment]
![Screenshot from 2022-06-16 23-17-46](https://user-images.githubusercontent.com/65948476/174104857-0de2e012-dec9-4d89-8fff-431226565556.png)
![Screenshot from 2022-06-16 23-18-35](https://user-images.githubusercontent.com/65948476/174104870-555110be-bade-4517-8130-3a85d4088d91.png)
![Screenshot from 2022-06-16 23-20-04](https://user-images.githubusercontent.com/65948476/174104880-d7581d57-fd3b-4a7c-a6d3-06808893504e.png)

nautilus and gtk 4 apps fine in gnome with left controls placement

this needs fix

- [ ] gtk2 colors
- [ ] gkt3 corners
- [ ] removing some stuff
- [ ] gnome-shell tweaks to window manager

**Comment by rxyhn** [comment]
damn so fucking cleannnnnnn 😍

need change colors for an alt-bg

main_bg = #061115
darker_bg = #0A1419
lighter_bg = #162026

so for the alt-bg you should use between darker_bg or lighter_bg 

to keep the beauty

**Comment by Deathemonic** [comment]
![image](https://user-images.githubusercontent.com/65948476/174194248-26aed19d-6031-49b0-bf66-d8d4c60edf35.png)

added this ``gtk-decoration-layout=close,maximize,minimize:menu`` to my ``~/.config/gtk-3.0/settings.ini`` and i got left controls

**Comment by Deathemonic** [comment]
but without the gnome-shell the sidepanel wont work

**Comment by Deathemonic** [comment]
@rxyhn 
need some feedback and what if it looks like in your computer, this is available you can install it here:
https://github.com/Deathemonic/Aesthetic-GTK/tree/whitesur-dev

**Comment by rxyhn** [comment]
![screensht_22-06-17_09:57:35](https://user-images.githubusercontent.com/93292023/174215962-9acf43af-0b6b-4724-826b-fd79ce7d3e06.png)
ic/Aesthetic-GTK/tree/whitesur-dev

> @rxyhn need some feedback and what if it looks like in your computer, this is available you can install it here: https://github.com/Deathemonic/Aesthetic-GTK/tree/whitesur-dev

@Deathemonic nice truly clean, just change some wrong [colors](https://github.com/Deathemonic/Aesthetic-GTK/issues/3#issuecomment-1157811071)

**Comment by Deathemonic** [comment]
alright, you want more preview install you can use a widget factory

``yay -S gtk3-demo gt4-demo awf-git``

also for some weird reason the gt4 widget factory display white titlebars and buttons idk why but normal apps just works fine maybe it's just my computer

**Comment by Deathemonic** [comment]
also the gdm should i also recolor it

**Comment by rxyhn** [comment]
> also the gdm should i also recolor it

nahhh didn't need to do that, just delete gdm theme, cause we need the gtk themes only

**Comment by Deathemonic** [comment]
there's also a kde variant which will color qt based apps like vlc

**Comment by rxyhn** [comment]
> there's also a kde variant which will color qt based apps like vlc

alright acceptable, so recolor gtk and qt colors, then remove unimportant part right?

**Comment by Deathemonic** [comment]
yeah

**Comment by Deathemonic** [comment]
@rxyhn should the theme be solid or transparent

**Comment by Deathemonic** [comment]
also im not removing some features from the source like nord, gdm, etc. simply cause it's time consuming and it doesn't affect the build release. if that's ok

**Comment by rxyhn** [comment]
> @rxyhn should the theme be solid or transparent

solid

> also im not removing some features from the source like nord, gdm, etc. simply cause it's time consuming and it doesn't affect the build release. if that's ok

is more better if remove it, I'm trying to make my repo not bloated as hell

**Comment by Deathemonic** [comment]
release a new beta with the fixed colors also try install the flatpak tweak and the snap tweak if those works

**Comment by rxyhn** [comment]
> release a new beta with the fixed colors, i need feedback for this try testing it out, there's a prebuild version on the `release` tree just extract it
> 
> ```shell
> tar -xf Aesthetic-Dark.tar.xz
> ```
> 
> also try install the flatpak tweak and the snap tweak if those works im still working on firefox theme and the kde theme, kde should probably done tommorow

![screensht_22-06-17_18:51:46](https://user-images.githubusercontent.com/93292023/174293104-c3ad160b-0115-4892-a5e6-092ffa16890b.png)

nice this is really cool themes,and yeah i've my own firefox theme, so you didn't need for working on firefox themes, just remove it.

**Comment by rxyhn** [comment]
![screensht_22-06-17_19:41:28](https://user-images.githubusercontent.com/93292023/174300286-9ca99523-62e9-4bd3-a23a-18947172c1c2.png)

also make the themes name is `Aesthetic-Night`

**Comment by Deathemonic** [comment]
ok, did the flatpak and snap work

**Comment by rxyhn** [comment]
> ok, did the flatpak and snap work

what should i do for it? i haven't use snap and flatpak before

**Comment by Deathemonic** [comment]
nevermind, also should i make a pull request to the dotfiles before the mac os concept update or ill wait after it releases

**Comment by rxyhn** [comment]
wait what, did the theme has finished?

**Comment by Deathemonic** [comment]
kinda, there's some stuff i haven't test out but most of the apps looks nice, im just asking if i can PR the gtk if the concept haven't been release yet

**Comment by Deathemonic** [comment]
if you think it's good for release ill make a PR

**Comment by Deathemonic** [comment]
kde theme will be tomorrow it should be quick cause I'll only need kvantum

**Comment by Deathemonic** [comment]
ok ill just make a pr when it's ready

**Comment by Deathemonic** [comment]
@rxyhn just created a PR

**Comment by Deathemonic** [comment]
@rxyhn GTK is ready, with no compression, KDE theme will upload today
